name: mininote
description: MiniNote – Cross-platform notes app powered by Flutter + Rust (FFI).
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  path_provider: ^2.1.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

msix_config:
  display_name: MiniNote
  publisher_display_name: Ahmad Abdelbary
  identity_name: io.github.ahmadabdelbary2001.mininote
  msix_version: 1.0.2.0
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: internetClient
  install_certificate: false
